export const LOAD_ISSUE_SUCCESS = 'LOAD_ISSUE_SUCCESS';
export const ADD_ISSUE_SUCCESS = 'ADD_ISSUE_SUCCESS';
export const DELETE_ISSUE_SUCCESS = 'DELETE_ISSUE_SUCCESS';
export const UPDATE_ISSUE_SUCCESS = 'UPDATE_ISSUE_SUCCESS';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const UPDATE_COUNT_SUCCESS = 'UPDATE_COUNT_SUCCESS';